# Homework 2

Please submit the solution to gradescope by 11:59 PM, Sept 26, Thursday.

**Name**: Robert Nachnani

**PID**: 730573785


# Problem 1  Sales Data Analysis (35 Points)
**Dataset:** You will work with a simulated dataset representing the monthly sales data for a fictional company over a period of 3 years (36 months). The dataset is provided as a NumPy array.

### 1.0 . Setup and Initialization

Import NumPy and initialize the dataset as a NumPy array.

In [18]:
import numpy as np

the_sales_data = np.array([207, 217, 244, 269, 247, 248, 273, 260, 243, 265, 263, 280,
                       310, 296, 313, 340, 336, 356, 335, 327, 374, 358, 376, 372,
                       405, 432, 425, 455, 443, 446, 439, 477, 454, 449, 494, 482])

#I changed the name of the original array in order to make my code run a lot smoother


### 1.1 Monthly Analysis (15 Points)
Using the `sales_data` array, perform the following tasks:
1. Calculate the total sales for each year, and store the result in a NumPy array `total_sales_per_year`. Display the `total_sales_per_year`. (2 points)

2. Calculate the average monthly sales for each year, and store the result in a NumPy array `average_monthly_sales_per_year`. Display the `average_monthly_sales_per_year`. (2 points)

3. Calculate the average season sales for each year, and store the result in a `3` by `4` NumPy array `average_season_sales_per_year`. Each row represent a year, and each column represent a season. Display the `average_season_sales_per_year`. (6 points)

4. Identify the month with the highest sales and the month with the lowest sales on average over the three year period. Store the numerical representation (1-12) of the month in the variables `max_sales_month` and `min_sales_month`. (5 points)

You can assume the years are in chronological order. For example, the first value represents sales in January of Year 1 and the last value represents sales in December of Year 3.


In [19]:
#Question 1
sales_data = sales_data.reshape(-1, 12)
total_sales_per_year = sales_data.sum(axis=1)
total_sales_per_year

array([3016, 4093, 5401])

In [20]:
average_monthly_sales_per_year = np.round(sales_data.mean(axis=1), 2)
average_monthly_sales_per_year

array([251.33, 341.08, 450.08])

In [21]:
seasons = sales_data.reshape(3 , 4 , 3)
average_season_sales_per_year = np.round(seasons.mean(axis=2), 2)
average_season_sales_per_year

array([[222.67, 254.67, 258.67, 269.33],
       [306.33, 344.  , 345.33, 368.67],
       [420.67, 448.  , 456.67, 475.  ]])

In [22]:
mean_sales_per_month = sales_data.mean(axis=0)
max_sales_month = np.argmax(mean_sales_per_month) + 1 
min_sales_month = np.argmin(mean_sales_per_month) + 1

max_sales_month , min_sales_month

(12, 1)

### 1.2 Growth Rate Calculation (5 Points)
Write a function `calculate_growth_rate(data)` that takes the `sales_data` array as input and returns the growth rates for each month in a NumPy array. You can assume the growth rate for the first month is 0.01.

Calculate the monthly growth rate of sales using the formula:

$$\text{growth_rate}[i] = \frac{\text{sales_data}[i] - \text{sales_data}[i-1]}{\text{sales_data}[i-1]}$$

Display the result of `calculate_growth_rate(sales_data)`.

In [24]:
def calculate_growth_rate(data):
    growth_rate = np.zeros(len(data))
    growth_rate[0] = 0.01
    for i in range(1, len(data)):
        growth_rate[i] = (data[i] - data[i-1]) / data[i-1]
    
    return growth_rate


growth_rate = calculate_growth_rate(the_sales_data)
growth_rate

array([ 0.01      ,  0.04830918,  0.12442396,  0.10245902, -0.08178439,
        0.00404858,  0.10080645, -0.04761905, -0.06538462,  0.09053498,
       -0.00754717,  0.06463878,  0.10714286, -0.04516129,  0.05743243,
        0.08626198, -0.01176471,  0.05952381, -0.05898876, -0.0238806 ,
        0.14373089, -0.04278075,  0.05027933, -0.0106383 ,  0.08870968,
        0.06666667, -0.0162037 ,  0.07058824, -0.02637363,  0.00677201,
       -0.01569507,  0.08656036, -0.04821803, -0.01101322,  0.10022272,
       -0.0242915 ])

### 1.3 Growth Rate Summary (5 Points)
Identify the following months:

*   The months in the past three years saw the largest increase and the largest decrease in sales (i.e. from January to February of Year 1 we saw the largest decrease in sales)
*   The month on average with the largest increase and largest decrease in sales

Show both the python code and conclusion.


In [25]:
growth_rate = calculate_growth_rate(the_sales_data)
growth_rate = growth_rate.reshape(-1,12)

#Part A
largest_increase = np.argmax(growth_rate) + 1
largest_decrease = np.argmin(growth_rate) + 1

#Part B
mean_growth_per_month = growth_rate.mean(axis=0)
max_growth_month = np.argmax(mean_growth_per_month) + 1 
min_growth_month = np.argmin(mean_growth_per_month) + 1
largest_decrease , largest_increase , min_growth_month , max_growth_month

(5, 21, 5, 4)

For part A, we see that month 5 or May-June of year 1 is where we see our largest decrease in sales, and September-October of year 2 has the largest increase across all three years.  In part B we see that the month with the lowest average increase is month 5 or May-June, while May-April has the largest average increase of all months.

### 1.4 Moving Average (5 points)

Calculate the 3-month moving average of the `sales_data` and store the result in a NumPy array called `moving_average`. The calculation starts from the third month in Year 1.


The three-period moving average for month $t$ is calculated as:


$$\text{MA}_3(t) = \frac{x_t + x_{t-1} + x_{t-2}}{3}.$$

Where:
- $x_t$ is the sales in month $t$,
- $x_{t-1}$ is the sales in month $t-1$,
- $x_{t-2}$ is the sales in month $t-2$.

Display the `moving_average`.

In [26]:
def calculate_moving_average(data, period=3):
    moving_average = np.zeros(len(data) - period + 1)
    
    for i in range(len(moving_average)):
        moving_average[i] = np.mean(data[i:i+period])
    
    return moving_average

moving_average = calculate_moving_average(sales_data)
moving_average

array([347.5])

### 1.5 Sales Anomaly Detection (5 points)

Write a function `sales_anomaly_detection(sales_data)` that takes the `sales_data` array as input, identify months where sales were significantly higher or lower than the previous month's sales (more than 12% change), and returns a dictionary mapping the month number (1-36) to the sales data for all anomalous months.

Display the result of `sales_anomaly_detection(sales_data)`.

In [30]:
def sales_anomaly_detection(sales_data):
    significant_sales_months = {}
    for i in range(1, len(sales_data)):
        change = (sales_data[i] - sales_data[i-1]) / sales_data[i-1]
        
        if abs(change) > 0.12:
            significant_sales_months[i + 1] = sales_data[i]

    return significant_sales_months

sales_anomaly_detection(the_sales_data)

{3: 244, 21: 374}

# Problem 2: Analysis on the diamonds dataset (65 points)

Here is a brief description of the key columns in the **`diamonds`** dataset from Seaborn:


**`Carat`**: The weight of the diamond (continuous variable). Larger diamonds have higher carat values.


**`Cut`**: The quality of the diamond's cut (categorical variable).


**`Color`**: The diamond’s color grade (categorical variable). 


**`Clarity`**: The clarity of the diamond (categorical variable), which indicates how free the diamond is from internal flaws (inclusions) or external blemishes. It ranges from `IF` (Internally Flawless) to `I3` (Included).


**`Depth`**: The total depth percentage (continuous variable). It’s the ratio of the depth of the diamond to its average diameter.


**`Table`**: The width of the diamond’s top relative to its widest point (expressed as a percentage).


**`Price`**: The price of the diamond in US dollars (continuous variable).


**`x`**: Length of the diamond in millimeters (continuous variable).


**`y`**: Width of the diamond in millimeters (continuous variable).


**`z`**: Depth of the diamond in millimeters (continuous variable).

This dataset provides valuable features for exploring the relationship between various attributes and the price of diamonds.

#### 2.1 Load the dataset from a `diamonds.csv`. (1 point)

#### 2.2 How many different levels are there in the `cut` column? Provide the names of all levels. (4 points)

#### 2.3 Create three new columns, `x_in_inch`, `y_in_inch`, and `z_in_inch`, which convert the units of the original `x`, `y`, and `z` from millimeters to inches. Print the new table. (5 points)

#### 2.4 Create a new column called `Normalized_depth`, which scales the depth values between 0 and 1. (10 points)

The equation to normalize the `depth` column is given as:

$$
\text{depth}_{\text{normalized}} = \frac{\text{depth} - \min(\text{depth})}{\max(\text{depth}) - \min(\text{depth})}
$$

Where:
- $ \text{depth} $ is the original value,
- $ \min(\text{depth}) $ is the minimum value in the `depth` column,
- $ \max(\text{depth}) $ is the maximum value in the `depth` column.

Print the new table.

#### 2.5 Select the rows from the entire table where `clarity` is `SI2`. Drop the columns `color` and `clarity`. Print the selected table. (5 points)

#### 2.6 Suppose we have a linear model that predicts the price of a diamond using the `carat` value:

$$
\text{Predicted Price}  = 7769 \times \text{carat} - 2262.
$$

In the selected table from 2.5, create a new column called `Predicted_Price`, which contains the predicted price using the above formula. Display the new table. (10 points)

#### 2.7 In the new table from 2.6, calculate the difference between the actual price and the predicted price. How many rows have a prediction error that is smaller than 20% of the actual price? (5 points)

#### 2.8 Sort the table in 2.7 by 'carat' column in increasing order. Display the first 3 rows and last 3 rows of the sorted table. (5 points). Concatenate the first 3 rows and last 3 rows into a new table. (5 points) (10 points in total)

#### 2.9 In the table from 2.7, what is the value of `carat` that has the smallest prediction error? What is the value of `carat` that has the largest prediction error. (5 points)

#### 2.10 In the orignal entire table, calculate the average prices for each level of cut. Display the result as a pd.Series. Does a better cut lead to a higher price? (10 points)

In [31]:
#Question 2.1
import pandas as pd
diamonds = pd.read_csv('diamonds.csv')
diamonds

Carat        Cut Color Clarity  depth  table  Price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [32]:
#Question 2.2
cut_names = diamonds['Cut'].unique()
len(cut_names) , cut_names

(5, array(['Ideal', 'Premium', 'Good', 'Very Good', 'Fair'], dtype=object))

In [33]:
#Question 2.3
diamonds['x_in_inch'] = diamonds['x'] / 25.4
diamonds['y_in_inch'] = diamonds['y'] / 25.4
diamonds['z_in_inch'] = diamonds['z'] / 25.4
diamonds

Carat        Cut Color Clarity  depth  table  Price     x     y     z  \
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43   
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31   
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31   
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63   
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75   
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...   
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50   
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61   
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56   
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74   
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64   

       x_in_inch  y_in_inch  z_in_inch  
0       0.155512   0.156693   0.095669  
1       0.153150   0.151181   0.090945  
2       0.159449   0.160236   0.090945  
3       0.165354   0.166535   0.103543  
4       0.170866   0.171260   0.108268  
...          ...        ...        ...  
53935   0.226378   0.226772   0.137795  
53936   0.224016   0.226378   0.142126  
53937   0.222835   0.223622   0.140157  
53938   0.242126   0.240945   0.147244  
53939   0.229528   0.231102   0.143307  

[53940 rows x 13 columns]

In [34]:
#Question 2.4
min_depth = diamonds['depth'].min()
max_depth = diamonds['depth'].max()
diamonds['Normalized_depth'] = (diamonds['depth'] - min_depth) / (max_depth - min_depth)
diamonds

Carat        Cut Color Clarity  depth  table  Price     x     y     z  \
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43   
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31   
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31   
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63   
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75   
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...   
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50   
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61   
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56   
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74   
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64   

       x_in_inch  y_in_inch  z_in_inch  Normalized_depth  
0       0.155512   0.156693   0.095669          0.513889  
1       0.153150   0.151181   0.090945          0.466667  
2       0.159449   0.160236   0.090945          0.386111  
3       0.165354   0.166535   0.103543          0.538889  
4       0.170866   0.171260   0.108268          0.563889  
...          ...        ...        ...               ...  
53935   0.226378   0.226772   0.137795          0.494444  
53936   0.224016   0.226378   0.142126          0.558333  
53937   0.222835   0.223622   0.140157          0.550000  
53938   0.242126   0.240945   0.147244          0.500000  
53939   0.229528   0.231102   0.143307          0.533333  

[53940 rows x 14 columns]

In [35]:
#Question 2.5
clarity_si2 = diamonds[diamonds['Clarity'] == 'SI2']
clarity_si2 = clarity_si2.drop(columns = ['Color' , 'Clarity'])
clarity_si2

Carat        Cut  depth  table  Price     x     y     z  x_in_inch  \
0       0.23      Ideal   61.5   55.0    326  3.95  3.98  2.43   0.155512   
4       0.31       Good   63.3   58.0    335  4.34  4.35  2.75   0.170866   
13      0.31      Ideal   62.2   54.0    344  4.35  4.37  2.71   0.171260   
14      0.20    Premium   60.2   62.0    345  3.79  3.75  2.27   0.149213   
16      0.30      Ideal   62.0   54.0    348  4.31  4.34  2.68   0.169685   
...      ...        ...    ...    ...    ...   ...   ...   ...        ...   
53902   0.77  Very Good   59.9   61.0   2753  5.98  6.01  3.59   0.235433   
53915   0.77      Ideal   62.1   56.0   2753  5.84  5.86  3.63   0.229921   
53928   0.79    Premium   61.4   58.0   2756  6.03  5.96  3.68   0.237402   
53938   0.86    Premium   61.0   58.0   2757  6.15  6.12  3.74   0.242126   
53939   0.75      Ideal   62.2   55.0   2757  5.83  5.87  3.64   0.229528   

       y_in_inch  z_in_inch  Normalized_depth  
0       0.156693   0.095669          0.513889  
4       0.171260   0.108268          0.563889  
13      0.172047   0.106693          0.533333  
14      0.147638   0.089370          0.477778  
16      0.170866   0.105512          0.527778  
...          ...        ...               ...  
53902   0.236614   0.141339          0.469444  
53915   0.230709   0.142913          0.530556  
53928   0.234646   0.144882          0.511111  
53938   0.240945   0.147244          0.500000  
53939   0.231102   0.143307          0.533333  

[9194 rows x 12 columns]

In [36]:
#Question 2.6
clarity_si2['Predicted_Price'] = 7760 * diamonds['Carat'] - 2262
clarity_si2

Carat        Cut  depth  table  Price     x     y     z  x_in_inch  \
0       0.23      Ideal   61.5   55.0    326  3.95  3.98  2.43   0.155512   
4       0.31       Good   63.3   58.0    335  4.34  4.35  2.75   0.170866   
13      0.31      Ideal   62.2   54.0    344  4.35  4.37  2.71   0.171260   
14      0.20    Premium   60.2   62.0    345  3.79  3.75  2.27   0.149213   
16      0.30      Ideal   62.0   54.0    348  4.31  4.34  2.68   0.169685   
...      ...        ...    ...    ...    ...   ...   ...   ...        ...   
53902   0.77  Very Good   59.9   61.0   2753  5.98  6.01  3.59   0.235433   
53915   0.77      Ideal   62.1   56.0   2753  5.84  5.86  3.63   0.229921   
53928   0.79    Premium   61.4   58.0   2756  6.03  5.96  3.68   0.237402   
53938   0.86    Premium   61.0   58.0   2757  6.15  6.12  3.74   0.242126   
53939   0.75      Ideal   62.2   55.0   2757  5.83  5.87  3.64   0.229528   

       y_in_inch  z_in_inch  Normalized_depth  Predicted_Price  
0       0.156693   0.095669          0.513889           -477.2  
4       0.171260   0.108268          0.563889            143.6  
13      0.172047   0.106693          0.533333            143.6  
14      0.147638   0.089370          0.477778           -710.0  
16      0.170866   0.105512          0.527778             66.0  
...          ...        ...               ...              ...  
53902   0.236614   0.141339          0.469444           3713.2  
53915   0.230709   0.142913          0.530556           3713.2  
53928   0.234646   0.144882          0.511111           3868.4  
53938   0.240945   0.147244          0.500000           4411.6  
53939   0.231102   0.143307          0.533333           3558.0  

[9194 rows x 13 columns]

In [37]:
#Question 2.7
clarity_si2['error'] = abs(clarity_si2['Price'] - clarity_si2['Predicted_Price'])
clarity_si2['percentage_error'] = clarity_si2['error'] / clarity_si2['Price']
filtered = clarity_si2[clarity_si2['percentage_error'] < .20]
filtered

Carat        Cut  depth  table  Price     x     y     z  x_in_inch  \
120     0.71      Ideal   62.3   56.0   2762  5.73  5.69  3.56   0.225591   
144     0.71      Ideal   61.6   55.0   2767  5.74  5.76  3.54   0.225984   
150     0.71    Premium   61.7   59.0   2768  5.71  5.67  3.51   0.224803   
280     0.72    Premium   62.0   60.0   2795  5.73  5.69  3.54   0.225591   
541     0.70      Ideal   60.6   57.0   2828  5.74  5.77  3.49   0.225984   
...      ...        ...    ...    ...    ...   ...   ...   ...        ...   
48978   0.36      Ideal   62.3   57.0    537  4.52  4.57  2.83   0.177953   
50283   0.37  Very Good   61.9   55.0    541  4.63  4.67  2.87   0.182283   
52627   0.35  Very Good   63.2   61.0    551  4.49  4.47  2.83   0.176772   
52628   0.35    Premium   62.0   58.0    551  4.50  4.47  2.78   0.177165   
53857   0.71    Premium   61.7   59.0   2743  5.67  5.71  3.51   0.223228   

       y_in_inch  z_in_inch  Normalized_depth  Predicted_Price  error  \
120     0.224016   0.140157          0.536111           3247.6  485.6   
144     0.226772   0.139370          0.516667           3247.6  480.6   
150     0.223228   0.138189          0.519444           3247.6  479.6   
280     0.224016   0.139370          0.527778           3325.2  530.2   
541     0.227165   0.137402          0.488889           3170.0  342.0   
...          ...        ...               ...              ...    ...   
48978   0.179921   0.111417          0.536111            531.6    5.4   
50283   0.183858   0.112992          0.525000            609.2   68.2   
52627   0.175984   0.111417          0.561111            454.0   97.0   
52628   0.175984   0.109449          0.527778            454.0   97.0   
53857   0.224803   0.138189          0.519444           3247.6  504.6   

       percentage_error  
120            0.175815  
144            0.173690  
150            0.173266  
280            0.189696  
541            0.120934  
...                 ...  
48978          0.010056  
50283          0.126063  
52627          0.176044  
52628          0.176044  
53857          0.183959  

[2189 rows x 15 columns]

In [38]:
#Question 2.8
sorted = clarity_si2.sort_values(by='Carat')
first_three = sorted.head(3)
last_three = sorted.tail(3)

concatenated = pd.concat([first_three, last_three])
concatenated

Carat        Cut  depth  table  Price     x     y     z  x_in_inch  \
14      0.20    Premium   60.2   62.0    345  3.79  3.75  2.27   0.149213   
43989   0.21    Premium   61.9   56.0    394  3.84  3.82  2.37   0.151181   
0       0.23      Ideal   61.5   55.0    326  3.95  3.98  2.43   0.155512   
27518   3.01       Good   63.9   60.0  18242  9.06  9.01  5.77   0.356693   
26100   3.04  Very Good   63.2   59.0  15354  9.14  9.07  5.75   0.359843   
27638   3.04    Premium   59.3   60.0  18559  9.51  9.46  5.62   0.374409   

       y_in_inch  z_in_inch  Normalized_depth  Predicted_Price   error  \
14      0.147638   0.089370          0.477778           -710.0  1055.0   
43989   0.150394   0.093307          0.525000           -632.4  1026.4   
0       0.156693   0.095669          0.513889           -477.2   803.2   
27518   0.354724   0.227165          0.580556          21095.6  2853.6   
26100   0.357087   0.226378          0.561111          21328.4  5974.4   
27638   0.372441   0.221260          0.452778          21328.4  2769.4   

       percentage_error  
14             3.057971  
43989          2.605076  
0              2.463804  
27518          0.156430  
26100          0.389110  
27638          0.149221

In [39]:
#Question 2.9
smallest_error_row = clarity_si2.loc[clarity_si2['percentage_error'].idxmin()]
smallest_carat = smallest_error_row['Carat']

largest_error_row = clarity_si2.loc[clarity_si2['percentage_error'].idxmax()]
largest_carat = largest_error_row['Carat']

smallest_carat , largest_carat

(0.35, 0.2)

In [40]:
#Question 2.10
average_price_by_cut = diamonds.groupby('Cut')['Price'].mean()
sorted_average = average_price_by_cut.sort_values(ascending = False)

average_price_by_cut , sorted_average

#The premium cut costs the most, and the quality descends as the price descends


(Cut
 Fair         4358.757764
 Good         3928.864452
 Ideal        3457.541970
 Premium      4584.257704
 Very Good    3981.759891
 Name: Price, dtype: float64,
 Cut
 Premium      4584.257704
 Fair         4358.757764
 Very Good    3981.759891
 Good         3928.864452
 Ideal        3457.541970
 Name: Price, dtype: float64)